-- MySQL Script generated by MySQL Workbench
-- Fri Mar  6 10:08:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema saveleafdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema saveleafdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `saveleafdb`;
CREATE SCHEMA IF NOT EXISTS `saveleafdb` ;
USE `saveleafdb` ;

-- -----------------------------------------------------
-- Table `saveleafdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saveleafdb`.`user` (
  `id_user` INT auto_increment NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `saveleafdb`.`bintype` (
  `id_type` INT auto_increment NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `saveleafdb`.`bins` (
  `id_bins` INT auto_increment NOT NULL,
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `BinType_id_type` INT,
  `description` VARCHAR(100),
  PRIMARY KEY (`id_bins`),
  foreign key(`BinType_id_type`) references `saveleafdb`.`bintype`(`id_type`) on update CASCADE on delete cascade
   )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `saveleafdb`.`privatebin` (
	`id_pivate_bin` INT auto_increment NOT NULL,
    `full` BOOL NOT NULL,
    `longitude` FLOAT NOT NULL,
	`latitude` FLOAT NOT NULL,
    `BinType_id_type` INT,
    `description` VARCHAR(100),
    `User_id` INT NOT NULL,
  PRIMARY KEY (`id_pivate_bin`),
  foreign key(`BinType_id_type`) references `saveleafdb`.`bintype`(`id_type`) on update CASCADE on delete cascade,
  foreign key(`User_id`) references `saveleafdb`.`user`(`id_user`) on update CASCADE on delete cascade
)
ENGINE = InnoDB;
